### ISSUE TITLE
cant unpack verge lite wf

### ISSUE THREAD

**Issue by ashtroy** [ghtalpo/py_amazfit_tools#3]
cant unpack virge lite wf https://amazfitwatchfaces.com/verge-lite/view/139

end of log:

2019-08-28 20:29:54,532 - root - ERROR - 
Traceback (most recent call last):
  File "D:\py_amazfit_tools-master\py_amazfit_tools-master\program.py", line 86, in readWatchFace
    reader.read()
  File "D:\py_amazfit_tools-master\py_amazfit_tools-master\watchFaceParser\reader.py", line 42, in read
    self._resources = Reader(self._stream).read(imagesCount)
  File "D:\py_amazfit_tools-master\py_amazfit_tools-master\resources\reader.py", line 38, in read
    bitmap = Reader(self._stream).read()
  File "D:\py_amazfit_tools-master\py_amazfit_tools-master\resources\image\reader.py", line 25, in read
    assert(False) # not implemented
AssertionError

**Comment by ghtalpo** [comment]
which tool did you use for packing? 

it has broken image header in it.

**Comment by ashtroy** [comment]
I don’t know which tool they use, I just want to edit wf for myself

**Comment by ghtalpo** [comment]
my tools is intended for pack/unpacking official wf.

wf that you've mentioned seems not correct .bin file.

to short, I cannot unpack yours. sorry.
